---
- name: initialize application via symfony.phar
  sudo_user: vagrant
  shell: creates={{ APPDIR }}/ chdir=/tmp
    symfony new --no-interaction --quiet {{ APPNAME }}-install
    && mv {{ APPNAME }}-install {{ APPDIR }}

