---
- name: setup PHP Composer
  shell: creates=composer.phar chdir={{ APPCOMMONDIR }}
    curl -sS https://getcomposer.org/installer | php
  sudo_user: vagrant

- name: setup framework installer
  shell: creates=symfony.phar chdir={{ APPCOMMONDIR }}
    curl -LsS http://symfony.com/installer > symfony.phar
  sudo_user: vagrant

- name: make framework installer executable
  file: path={{ APPCOMMONDIR }}/symfony.phar mode='ugo+x'

- name: symlink PHAR files
  file: src={{ APPCOMMONDIR }}/{{item}}.phar dest=/usr/local/bin/{{item}} state=link
  with_items:
    - composer
    - symfony
